language: python
python:
  - "3.9"
install:
  - pip install flask
  - pip install flask-sqlalchemy
  - pip install requests
  - pip install flask_login
  - pip install pytest-cov

# Run tests
script:
  - python -m pytest --cov

